version: '3'
services:
  fastapi_yolo:
    build: .
    restart: "always"
    volumes:
    - ./:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: uvicorn main:app --host 0.0.0.0 --port 8080
